### ISSUE TITLE
前缀位置添加有错误

### ISSUE THREAD

**Issue by HSpp** [ymrdf/postcss-plugin-namespace#17]
`@-webkit-keyframes v-modal-in {
  #App 0% {
    opacity: 0;
  }
}
@-webkit-keyframes v-modal-out {
  #App to {
    opacity: 0;
  }
}`

**Comment by HSpp** [comment]
修改下判断条件
`function specailTest (rule) {
  if (rule.parent && rule.parent.name === 'keyframes' && rule.parent.name.includes('keyframes')) {
    return true
  }
  return false
}`

**Comment by ymrdf** [comment]
resolved
